In [214]:
import numpy as np

#np.save('C:\\Users\\Jesse Frank\\OneDrive - Specialized Bicycle Components\\Body Geometry team\\Projects\\Aetrex Object Files\\python_files\\left_foot_gg_searted.npy','left_foot_GG_Seated.asc')

%run test_foot_file_discrete_metrics_v3.py

5_left_foot_gg_seated.npy
19.80328106880188


In [218]:
fname = 'C:\\Users\\Jesse Frank\\OneDrive - Specialized Bicycle Components\\Body Geometry team\\Projects\\Aetrex Object Files\\python_files\\right_foot_GG_Seated.obj'
tt = np.array('C:\\Users\\Jesse Frank\\OneDrive - Specialized Bicycle Components\\Body Geometry team\\Projects\\Aetrex Object Files\\python_files\\left_foot_GG_Seated.obj')

array('C:\\Users\\Jesse Frank\\OneDrive - Specialized Bicycle Components\\Body Geometry team\\Projects\\Aetrex Object Files\\python_files\\left_foot_GG_Seated.obj',
      dtype='<U147')

In [136]:
aa = np.load('C:\\Users\\Jesse Frank\\OneDrive - Specialized Bicycle Components\\Body Geometry team\\Projects\\Aetrex Object Files\\python_files\\Daniel Feeney Right_info.npy', allow_pickle = True)

In [138]:
aa

array([array([[5.30907e-02, 6.91470e-02, 4.28009e-05],
              [5.53687e-02, 6.96561e-02, 1.58359e-05],
              [5.53839e-02, 6.74535e-02, 5.56118e-05],
              ...,
              [8.61589e-02, 2.97784e-01, 9.60787e-02],
              [8.53536e-02, 2.97179e-01, 9.92781e-02],
              [8.26772e-02, 2.99276e-01, 9.90673e-02]]),
       array([[   0,    1,    2],
              [   3,    0,    2],
              [   4,    1,    0],
              ...,
              [6332, 6331, 6327],
              [6328, 6335, 6334],
              [6333, 6328, 6334]]),
       array([[-9.28327e-03, -2.01028e-02, -9.99755e-01,  5.30907e-02,
                6.91470e-02,  4.28009e-05],
              [-9.28327e-03, -2.01028e-02, -9.99755e-01,  5.53687e-02,
                6.96561e-02,  1.58359e-05],
              [-9.28327e-03, -2.01028e-02, -9.99755e-01,  5.53839e-02,
                6.74535e-02,  5.56118e-05],
              ...,
              [ 5.87620e-01,  7.47263e-01,  3.10324e-01,  8.

In [152]:
import openmesh as om

In [157]:
testM = om.read_trimesh(fname)
print(testM)

In [179]:
tt = np.array(testM)
tt

array(<openmesh.TriMesh object at 0x0000026D5C4C1B70>, dtype=object)

In [182]:
color_array = testM.vertex_property_array('Normal')
#np.save('C:\\Users\\Jesse Frank\\OneDrive - Specialized Bicycle Components\\Body Geometry team\\Projects\\Aetrex Object Files\\python_files\\4_left_foot_gg_seated.npy',color_array)
np.save('tester',color_array)

array([nan, nan, nan, ..., nan, nan, nan])

In [171]:
bb = np.load('C:\\Users\\Jesse Frank\\OneDrive - Specialized Bicycle Components\\Body Geometry team\\Projects\\Aetrex Object Files\\python_files\\4_left_foot_gg_seated.npy')
bb

array([nan, nan, nan, ..., nan, nan, nan])

In [62]:
import pyglet
import pywavefront as pwave
from pywavefront import visualization

In [112]:
obj = pwave.Wavefront(fname,collect_faces=True, parse = True)


In [113]:
obj

In [216]:
aa = np.array(obj)
aa

array(<pywavefront.wavefront.Wavefront object at 0x0000026D5AD5B3D0>,
      dtype=object)

In [161]:
np.save('C:\\Users\\Jesse Frank\\OneDrive - Specialized Bicycle Components\\Body Geometry team\\Projects\\Aetrex Object Files\\python_files\\1_left_foot_gg_seated.npy', fname, allow_pickle = True)

In [103]:
# Iterate vertex data collected in each material
for name, material in obj.materials.items():
    # Contains the vertex format (string) such as "T2F_N3F_V3F"
    # T2F, C3F, N3F and V3F may appear in this string
    material.vertex_format
    # Contains the vertex list of floats in the format described above
    material.vertices
    # Material properties
    material.diffuse
    material.ambient
    material.texture

In [63]:
window = pyglet.window.Window(800, 520,caption='3D Face', resizable=False)
visualization.draw(test)

In [111]:
material.texture

In [125]:
import pandas as pd
col_names = ['col1','col2','col3','col4','col5']
obj_test = pd.read_csv(fname, sep="\s+", names = col_names)

In [126]:
print(obj_test)

      col1        col2        col3        col4        col5
0        v    0.289346   0.0637892  0.00242001         NaN
1        v    0.289558   0.0665683  0.00246076         NaN
2        v    0.292281   0.0656155  0.00255228         NaN
3        v    0.291293    0.063968  0.00262356         NaN
4        v    0.286302    0.065838  0.00248566         NaN
...    ...         ...         ...         ...         ...
19209    f  6397//6400  6401//6400  6379//6400  6399//6400
19210    f  6378//6401  6400//6401  6373//6401  6399//6401
19211    f  6402//6402  6396//6402  6406//6402  6403//6402
19212    f  6405//6403  6404//6403  6383//6403  6403//6403
19213    f  6406//6404  6392//6404  6405//6404  6403//6404

[19214 rows x 5 columns]


In [127]:
np.save('C:\\Users\\Jesse Frank\\OneDrive - Specialized Bicycle Components\\Body Geometry team\\Projects\\Aetrex Object Files\\python_files\\2_left_foot_gg_seated.npy', obj_test)

In [128]:
bb = np.load('C:\\Users\\Jesse Frank\\OneDrive - Specialized Bicycle Components\\Body Geometry team\\Projects\\Aetrex Object Files\\python_files\\2_left_foot_gg_seated.npy', allow_pickle = True)
print(bb)

[['v' '0.289346' '0.0637892' '0.00242001' nan]
 ['v' '0.289558' '0.0665683' '0.00246076' nan]
 ['v' '0.292281' '0.0656155' '0.00255228' nan]
 ...
 ['f' '6402//6402' '6396//6402' '6406//6402' '6403//6402']
 ['f' '6405//6403' '6404//6403' '6383//6403' '6403//6403']
 ['f' '6406//6404' '6392//6404' '6405//6404' '6403//6404']]


In [150]:
from stl import mesh
mpc = mesh.Mesh.from_file(fname)

AssertionError: File too large, got 825636150 triangles which exceeds the maximum of 100000000

In [219]:
mpc = PyntCloud.from_file(fname)
print(mpc)

PyntCloud
6462 points with 3 scalar fields
6460 faces in mesh
0 kdtrees
0 voxelgrids
Centroid: 0.07862287759780884, 0.20311841368675232, 0.034206390380859375
Other attributes:



In [220]:
mpc.to_file('C:\\Users\\Jesse Frank\\OneDrive - Specialized Bicycle Components\\Body Geometry team\\Projects\\Aetrex Object Files\\python_files\\4_right_foot_gg_seated.npz')
bb = np.load('C:\\Users\\Jesse Frank\\OneDrive - Specialized Bicycle Components\\Body Geometry team\\Projects\\Aetrex Object Files\\python_files\\4_right_foot_gg_seated.npz',allow_pickle = True)
bb.files

['points']

In [222]:
bb['points']
np.save('C:\\Users\\Jesse Frank\\OneDrive - Specialized Bicycle Components\\Body Geometry team\\Projects\\Aetrex Object Files\\python_files\\5_right_foot_gg_seated.npy',bb['points'])

In [224]:
v_f_n = np.load('C:\\Users\\Jesse Frank\\OneDrive - Specialized Bicycle Components\\Body Geometry team\\Projects\\Aetrex Object Files\\python_files\\5_right_foot_gg_seated.npy',allow_pickle = True)

In [225]:
point_cloud = v_f_n[0]
faces = v_f_n[1]
normals = v_f_n[2]

In [228]:
normals

(0.05689, 0.0810047, 0.00132736, 0.206594, 0.199813, -0.957807)